language: ruby
rvm:
  - 1.9.3
before_install:
  - "bundle --version"
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq -y graphicsmagick > /dev/null
  - sudo apt-get install -qq -y libreoffice-common > /dev/null
  - sudo apt-get install -qq -y sphinxsearch > /dev/null
  - sudo apt-get install -qq -y inkscape > /dev/null
before_script:
  - "rake create_a_secret"
  - "cp config/database.yml.example config/database.yml"
  - "rake db:create"
  - "rake db:schema:load"
  - "rake db:test:prepare"
  - "rake RAILS_ENV=test db:fixtures:load"
  - "rake RAILS_ENV=test ts:index ts:start"
notifications:
  email: false

